import type { Metadata } from 'next';
import { manrope, montserrat, unbounded } from './ui/fonts';
import './globals.css';
import { Header } from '@/components/widgets';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${manrope.variable} ${montserrat.variable} ${unbounded.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
