import type { Metadata } from 'next';
import { manrope, montserrat } from './ui/fonts';
import './globals.css';
import { Header } from '@/components/shared';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${manrope.variable} ${montserrat.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
